# Zmienne środowiskowe (Docker / CI). Domyślne wartości = uruchomienie lokalne z docker-compose flexo-db
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flexo_local_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:flexo_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:StrongFlexoPassword123}

# To musi zostać, żeby Hibernate wiedział, co robić, nawet jeśli baza nie wstanie od razu
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8192